### ISSUE TITLE
No records to show!

### ISSUE THREAD

**Issue by Bamux** [hewisaurus/PrancingTurtle#3]
In my local installation with the data from the PTBasicData-IncGuild-5Sessions.sql, I see no records even if I add new sessions.
![image](https://user-images.githubusercontent.com/18372137/31938710-999f5936-b8b8-11e7-8e5f-5a8cd91d164d.png)

**Comment by hewisaurus** [comment]
That's the case because the 15-20 minute leaderboards scheduled task isn't running.
Two ways to do this - the easiest being to insert a row into the **ScheduledTask** table with the Name equal to **EncounterPlayerStatistics** and **ScheduleMinutes** set to whatever timespan you'd like it to be run at.
Alternatively, put together a method that runs the same code as what gets executed for that task - see **/PrancingTurtle/Helpers/Scheduling/Jobs/EncounterPlayerStatistics.cs** for this.
